- name: "Ansible Instance creation"
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        aws_access_key: <insert access key>
        aws_secret_key: <insert sercret key>
        region: us-east-1
        key_name: <Insert name of key pair>
        instance_type: <enter instance type>
        image_id: ami-0e86e20dae9224db8
        security_groups:  
          - sg-077a4a27e9b9e80a2
        subnet_id: subnet-04fd6d8b7687e3c02
        tags:
          Name: "{{ item.name }}"
        user_data: |
          #!/bin/bash
          apt update
          apt install -y ansible
          sudo wget https://raw.githubusercontent.com/Bar-Tubul/CD-FWS/main/ansible/packages-installation.yml -O /home/ubuntu/packages-installation.yml
          ansible-playbook /home/ubuntu/packages-installation.yml
        count: 1
        name: "{{ item.name }}"
      loop:
        - { name: "bar-jenkins-1" }
      register: ec2
