---
- name: Install Docker, Python3, Boto3, Jenkins, and OpenJDK 17 on Ubuntu
  hosts: localhost
  become: true

  tasks:
    - name: Update the packages
      command: apt update

    - name: Install Docker
      command: apt install -y docker.io

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: Add the Docker group to the ubuntu user
      user:
        name: "ubuntu"
        groups: docker
        append: yes

    - name: Add the Docker group to the jenkins user
      user:
        name: "jenkins"
        groups: docker
        append: yes

    - name: Install Python3
      command: apt install -y python3

    - name: Install pip3
      command: apt install -y python3-pip

    - name: Install Boto3 via apt (Avoiding pip error)
      command: apt install -y python3-boto3

    - name: Install OpenJDK 17
      command: apt install -y fontconfig openjdk-17-jre

    - name: Install Jenkins
      shell: |
        sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
          https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
          https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
          /etc/apt/sources.list.d/jenkins.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y jenkins

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: true



