---
- name: Install Docker, Python3, Boto3, Jenkins, and OpenJDK 17 on Ubuntu
  hosts: localhost
  become: true

  tasks:
    - name: Update the packages
      command: apt update

    - name: Install Docker
      command: apt install -y docker.io

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: Add the Docker group to the ubuntu user
      user:
        name: "ubuntu"
        groups: docker
        append: yes

    - name: Add the Docker group to the jenkins user
      user:
        name: "jenkins"
        groups: docker
        append: yes

    - name: Install Python3
      command: apt install -y python3

    - name: Install pip3
      command: apt install -y python3-pip

    - name: Install Boto3
      pip:
        name: boto3
        executable: pip3

    - name: Install fontconfig and OpenJDK 17
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - fontconfig
        - openjdk-17-jre

    - name: Verify Java version
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      debug:
        var: java_version_output.stdout

    - name: Install Jenkins (import key)
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes


